<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?= $this->config('site')['name'] ?></title>
    </head>
    <body>
        <nav>
            <a href="<?= $this->url('UserController', 'list', 'User') ?>">Users</a>
        </nav>
        <hr />
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2020 - <?= date('Y') ?> Powered by Tiny Framework.</p>
            </footer>
        </div>
    </body>
</html>
